development:
  adapter: mysql2
  encoding: utf8
  database: zumba_development
  username: root
  password: ryanitsme
  host: localhost
test: &test
  adapter: mysql2
  encoding: utf8
  database: zumba_test
  username: root
  password: ryanitsme
  host: localhost

cucumber:
  <<: *test